name: Compilar e implementar la aplicación de .NET Core en la aplicación de funciones SalaryCalculatorEc
on:
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: SalaryCalculatorEc
  AZURE_FUNCTIONAPP_PACKAGE_PATH: SalaryCalculator/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: SalaryCalculator
  DOTNET_CORE_VERSION_INPROC: 8.0.x
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Clean publish directory
      run: |
        rm -rf '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        mkdir -p '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        
    - name: Publish Function App
      run: |
        dotnet publish './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}' \
          --configuration Release \
          --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output' \
          --runtime win-x64 \  # Cambia a linux-x64 si es Linux
          --self-contained false \
          /p:BuildProjectReferences=false
        
        # Verifica los archivos publicados
        ls -R '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}