name: Compilar e implementar la aplicación de .NET Core en la aplicación de funciones SalaryCalculatorEc
on:
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: SalaryCalculatorEc
  AZURE_FUNCTIONAPP_PACKAGE_PATH: SalaryCalculator/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: SalaryCalculator
  DOTNET_CORE_VERSION_INPROC: 8.0.x
  FUNCTIONS_WORKER_RUNTIME: dotnet-isolated 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup .NET Core (for inproc extensions)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION_INPROC }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish_output"
    - name: Fix Publish Structure
      run: |
        echo "Moviendo archivos a la raíz del paquete..."
        mv "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish_output"/* "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        rmdir "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish_output"
        echo "Estructura corregida:"
        ls -la "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Verify Published Files
      run: |
        echo "Contenido de ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}:"
        ls -laR '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        echo ""
        echo "¿Existe host.json?"
        test -f '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/host.json' && echo "SÍ" || echo "NO"
